# yml语法备忘
# ports: 导出端口。格式可以是：
#       ports:-"3000"-"8000:8000"-"127.0.0.1:8001:8001"
# expose：导出端口，但不映射到宿主机的端口上。它仅对links的容器开放。格式直接指定端口号即可。
# 参考 http://debugo.com/docker-compose/

version: '2'
services:
    mysqlW:
        #build: ./mysql
        image: worden/mysql
        container_name: "lx_mysql"
        ports:
            - "3306:3306"
        volumes:
            - ~/Code/dockerEnv/src/mysql/data:/var/lib/mysql
            - ~/Code/worden:/worden
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: lanxin_local_test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            mynetwork:
                ipv4_address: 172.20.0.2

    redisW:
        #build: ./redis
        image: worden/redis
        container_name: lx_redis
        ports:
            - "6379:6379"
        networks:
            mynetwork:
                ipv4_address: 172.20.0.3

    elasticsearchW:
        #build: ./elasticsearch
        image: worden/elasticsearch
        container_name: lx_es
        volumes:
            - ~/Code/dockerEnv/src/es_data:/usr/share/elasticsearch/data
            # - ~/Code/dockerEnv/src/config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            mynetwork:
                ipv4_address: 172.20.0.4

    #mongodbW:
        #build: ./mysql
        #image: worden/mongodb
        #container_name: "lx_mongodb"
        #ports:
            #- "27017:27017"
        #volumes:
            #- ~/Code/worden:/worden
            #- ~/Code/lx:/lx
        #restart: always
        #environment:
             #MONGO_INITDB_ROOT_USERNAME: root
             #MONGO_INITDB_ROOT_PASSWORD: 123456
        #networks:
            #mynetwork:
                #ipv4_address: 172.20.0.9

    phpW:
        #build: ./php
        image: worden/php
        container_name: lx_php
        ports:
            - "9000:9000"
        links:
            - "mysqlW"
            - "redisW"
            - "elasticsearchW"
        volumes:
            - ~/Code/worden:/worden
            - ~/Code/lx:/lx
        networks:
            mynetwork:
                ipv4_address: 172.20.0.5

    nginxW:
        #build: ./nginx
        image: worden/nginx
        container_name: lx_nginx
        ports:
            - "80:80"
            - "8080:8080"
            - "8083:8083"
        links:
            - "phpW"
        volumes_from:
            - "phpW"
        volumes:
            - ~/Code/dockerEnv/src/nginx/logs:/var/log/nginx
        networks:
            mynetwork:
                ipv4_address: 172.20.0.6


    golangW:
        #build: ./golang
        image: worden/golang
        container_name: lx_golang
        links:
            - "mysqlW"
            - "redisW"
        volumes:
            - ~/Code/worden:/worden
        stdin_open: true
        tty: true
        networks:
            mynetwork:
                ipv4_address: 172.20.0.7


    pythonW:
        #build: ./python
        image: worden/python
        container_name: lx_python
        links:
            - "mysqlW"
            - "redisW"
        volumes:
            - ~/Code/worden:/worden
        stdin_open: true
        tty: true
        networks:
            mynetwork:
                ipv4_address: 172.20.0.8
    nodejsW:
        #build: ./python
        image: worden/nodejs
        container_name: lx_nodejs
        links:
            - "redisW"
            #- "mongodbW"
        volumes:
            - ~/Code/worden:/worden
            - ~/Code/lx:/lx
        ports:
            - "1338:1338"
        stdin_open: true
        tty: true
        networks:
            mynetwork:
                ipv4_address: 172.20.0.10
    parse:
        image: parseplatform/parse-server
        ports:
            - 1337:1337
        links:
            - "mongodbW"
        environment:
            - PARSE_SERVER_APPLICATION_ID=b32h7SrhRXGiD3Ubvt2KQHtiR3VPrPgYWIxOlZ35
            - PARSE_SERVER_MASTER_KEY=wUiX7rQ0B58FeT2IdxbaK6hn3JXWPhb2998oq9C7
            - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/parse
        restart: always

    dashboard:
        image: parseplatform/parse-dashboard
        ports:
            - 4040:4040
        environment:
            - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
            - PARSE_DASHBOARD_APP_ID=b32h7SrhRXGiD3Ubvt2KQHtiR3VPrPgYWIxOlZ35
            - PARSE_DASHBOARD_MASTER_KEY=wUiX7rQ0B58FeT2IdxbaK6hn3JXWPhb2998oq9C7
            - PARSE_DASHBOARD_APP_NAME=MyApp
            - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
            - PARSE_DASHBOARD_USER_ID=admin
            - PARSE_DASHBOARD_USER_PASSWORD=123456

#networks 要与上分的service目录同级别,下方缩进不能有错误
networks:
    mynetwork:
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1
