# yml语法备忘
# ports: 导出端口。格式可以是：
#       ports:-"3000"-"8000:8000"-"127.0.0.1:8001:8001"
# expose：导出端口，但不映射到宿主机的端口上。它仅对links的容器开放。格式直接指定端口号即可。
# 参考 http://debugo.com/docker-compose/

version: '2'
services:
    mysqlW:
        #build: ./mysql
        image: worden/mysql
        container_name: "lx_mysql"
        ports:
            - "3306:3306"
        volumes:
            - C:/Users/wordenfan/Code/dockerEnv/src/mysql/data:/var/lib/mysql
            - C:/Users/wordenfan/Code/worden:/worden
            #- ~/Code/dockerEnv/src/mysql/data:/var/lib/mysql
            #- ~/Code/worden:/worden
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: lanxin_local_test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            mynetwork:
                ipv4_address: 172.20.0.2

    redisW:
        #build: ./redis
        image: worden/redis
        container_name: lx_redis
        ports:
            - "6379:6379"
        networks:
            mynetwork:
                ipv4_address: 172.20.0.3

    phpW:
        #build: ./php
        image: worden/php
        container_name: lx_php
        ports:
            - "9000:9000"
            - "50051:50051"
            - "50052:50052"
        links:
            - "mysqlW"
            - "redisW"
            #- "elasticsearchW"
        volumes:
            - C:/Users/wordenfan/Code:/worden
            #- ~/Code/worden:/worden
            #- ~/Code/lx:/lx
        networks:
            mynetwork:
                ipv4_address: 172.20.0.5

    nginxW:
        #build: ./nginx
        image: worden/nginx
        container_name: lx_nginx
        ports:
            - "80:80"
            - "8080:8080"
            - "8083:8083"
        links:
            - "phpW"
        volumes_from:
            - "phpW"
        volumes:
            - C:/Users/wordenfan/Code/dockerEnv/src/nginx/logs:/var/log/nginx
            #- ~/Code/dockerEnv/src/nginx/logs:/var/log/nginx
        networks:
            mynetwork:
                ipv4_address: 172.20.0.6
                    

#networks 要与上分的service目录同级别,下方缩进不能有错误
networks:
    mynetwork:
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1
