# docker build -t worden/mysql ./mysql
# docker run -d --name=mysqlW -p 3306:3306 -v ~/Code/worden/docker_test/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -it worden/mysql


FROM mysql:5.6
