# yml语法备忘
# ports: 导出端口。格式可以是：
#       ports:-"3000"-"8000:8000"-"127.0.0.1:8001:8001"
# expose：导出端口，但不映射到宿主机的端口上。它仅对links的容器开放。格式直接指定端口号即可。
# 参考 http://debugo.com/docker-compose/

mysqlW:
    #build: ./mysql
    image: worden/mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/Code/worden/docker_data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

mongoW:
    #build: ./mysql
    image: worden/mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/Code/worden/docker_data/mongo:/data/db

redisW:
    #build: ./redis
    image: worden/redis
    ports:
      - "6379:6379"

elasticsearchW:
  #build: ./elasticsearch
  image: worden/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

phpW:
    #build: ./php
    image: worden/php
    ports:
      - "9000:9000"
    links:
      - mysqlW
      - mongoW
      - redisW
      - elasticsearchW
    volumes:
      - ~/Code/worden:/worden
      - ~/Code/sipai:/sipai

nginxW:
    #build: ./nginx
    image: worden/nginx
    ports:
      - "80:80"
    links:
      - phpW
    volumes_from:
      - phpW
    volumes:
      - ~/Code/docker_worden/src/nginx/logs:/var/log/nginx

# golangW:
#     #build: ./golang
#     image: worden/golang
#     links:
#       - mysqlW
#       - redisW
#     volumes:
#       - ~/Code/worden:/worden

# pythonW:
#     #build: ./python
#     image: worden/python
#     command:
#       python ./python/app.py
#     ports:
#       - "5000:5000"
#     links:
#       - mysqlW
#       - mongoW
#       - redisW
#       - elasticsearchW
#     volumes:
#       - ~/Code/worden/python:/worden/python
