
mysql_w:
    #build: ./mysql
    image: worden/mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/Code/worden/docker_test/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

redis_w:
    #build: ./redis
    image: worden/redis
    ports:
      - "6379:6379"

php_w:
    #build: ./php
    image: worden/php
    ports:
      - "9000:9000"
    links:
      - mysql_w
      - redis_w
    volumes:
      - ~/Code/worden:/worden

nginx_w:
    #build: ./nginx
    image: worden/nginx
    ports:
      - "80:80"
    links:
      - php_w
    volumes_from:
      - php_w
