# yml语法备忘
# ports: 导出端口。格式可以是：
#       ports:-"3000"-"8000:8000"-"127.0.0.1:8001:8001"
# expose：导出端口，但不映射到宿主机的端口上。它仅对links的容器开放。格式直接指定端口号即可。
# 参考 http://debugo.com/docker-compose/

version: '2'
services:
  mysqlW:
      #build: ./mysql
      image: worden/mysql
      container_name: "lx_mysql"
      ports:
        - "3306:3306"
      volumes:
        - ~/Code/dockerEnv/src/mysql/data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: lanxin_local_test
        MYSQL_USER: root
        MYSQL_PASSWORD: root

  redisW:
      #build: ./redis
      image: worden/redis
      container_name: lx_redis
      ports:
        - "6379:6379"

  elasticsearchW:
      #build: ./elasticsearch
      image: worden/elasticsearch
      container_name: lx_es
      volumes:
         - ~/Code/dockerEnv/src/es_data:/usr/share/elasticsearch/data
      #   - ~/Code/dockerEnv/src/config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      environment:
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         - discovery.type=single-node
      ports:
         - "9200:9200"
         - "9300:9300"

  phpW:
      #build: ./php
      image: worden/php
      container_name: lx_php
      ports:
        - "9000:9000"
      links:
        - "mysqlW"
        - "redisW"
        - "elasticsearchW"
      volumes:
        - ~/Code/worden:/worden
        - ~/Code/lx:/lx

  nginxW:
      #build: ./nginx
      image: worden/nginx
      container_name: lx_nginx
      ports:
        - "80:80"
      links:
        - "phpW"
      volumes_from:
        - "phpW"
      volumes:
        - ~/Code/dockerEnv/src/nginx/logs:/var/log/nginx


  golangW:
      #build: ./golang
      image: worden/golang
      container_name: lx_golang
      links:
        - "mysqlW"
        - "redisW"
      volumes:
        - ~/Code/worden:/worden
      stdin_open: true
      tty: true


  pythonW:
      #build: ./python
      image: worden/python
      container_name: lx_python
      links:
        - "mysqlW"
        - "redisW"
      volumes:
        - ~/Code/worden:/worden
      stdin_open: true
      tty: true
