# yml语法备忘
# ports: 导出端口。格式可以是：
#       ports:-"3000"-"8000:8000"-"127.0.0.1:8001:8001"
# expose：导出端口，但不映射到宿主机的端口上。它仅对links的容器开放。格式直接指定端口号即可。
# 参考 http://debugo.com/docker-compose/

version: '2'
services:
    # nsqd集群
    nsq-admin:
        image: nsqio/nsq:v1.2.0
        command: /nsqadmin -lookupd-http-address nsq-nsqlookupd1:4161 -lookupd-http-address nsq-nsqlookupd2:4261
        ports:
        - "4171:4171"
    nsq-nsqd1:
        image: nsqio/nsq:v1.2.0
        hostname: nsq-nsqd1
        command: /nsqd -tcp-address 0.0.0.0:4150 -data-path /usr/local/nsq/bin/data --http-address 0.0.0.0:4151 -lookupd-tcp-address nsq-nsqlookupd1:4160 -lookupd-tcp-address nsq-nsqlookupd2:4260 -broadcast-address nsq-nsqd1
        volumes:
        - "./data1:/usr/local/nsq/bin/data"
        ports:
        - "4150:4150" #tcp
        - "4151:4151" #http
    nsq-nsqd2:
        image: nsqio/nsq:v1.2.0
        hostname: nsq-nsqd2
        command: /nsqd -tcp-address 0.0.0.0:4250 -data-path /usr/local/nsq/bin/data -http-address 0.0.0.0:4251 -lookupd-tcp-address nsq-nsqlookupd1:4160 -lookupd-tcp-address nsq-nsqlookupd2:4260 -broadcast-address=nsq-nsqd2
        volumes:
        - "./data2:/usr/local/nsq/bin/data"
        ports:
        - "4250:4250"
        - "4251:4251"
    nsq-nsqd3:
        image: nsqio/nsq:v1.2.0
        hostname: nsq-nsqd3
        command: /nsqd -tcp-address 0.0.0.0:4350 -data-path /usr/local/nsq/bin/data -http-address 0.0.0.0:4351 -lookupd-tcp-address nsq-nsqlookupd1:4160 -lookupd-tcp-address nsq-nsqlookupd2:4260 -broadcast-address=nsq-nsqd3
        volumes:
        - "./data3:/usr/local/nsq/bin/data"
        ports:
        - "4350:4350"
        - "4351:4351"
    nsq-nsqlookupd1:
        image: nsqio/nsq:v1.2.0
        command: /nsqlookupd -http-address 0.0.0.0:4161 -tcp-address 0.0.0.0:4160 -broadcast-address nsq-nsqlookupd1
        ports:
        - "4160:4160"
        - "4161:4161"
    nsq-nsqlookupd2:
        image: nsqio/nsq:v1.2.0
        command: /nsqlookupd -http-address 0.0.0.0:4261 -tcp-address 0.0.0.0:4260 -broadcast-address nsq-nsqlookupd2
        ports:
        - "4260:4260"
        - "4261:4261"

#networks 要与上分的service目录同级别,下方缩进不能有错误
networks:
    mynetwork:
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1
